<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>wasi-wasm</RuntimeIdentifier>
    <WasmGenerateAppBundle>false</WasmGenerateAppBundle>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NativeLib>Shared</NativeLib>
    <RunAOTCompilation>true</RunAOTCompilation>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Realm.MapAPI">
      <HintPath>lib/Realm.MapAPI.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <DirectPInvoke Include="env" />
    <LinkerArg Include="-Wl,--allow-undefined" />
  </ItemGroup>
  <Target Name="EnableAotLate" BeforeTargets="ImportRuntimeIlcPackageTarget;IlcCompile;_ComputeAssembliesToCompileToNative">
    <PropertyGroup>
      <PublishAot>true</PublishAot>
      <IlcLlvmTarget>wasm32-unknown-wasi</IlcLlvmTarget>
    </PropertyGroup>
  </Target>
  <Target Name="ClearComponentWit" BeforeTargets="LinkNative;LinkNativeLlvm">
    <ItemGroup>
      <WasmComponentTypeWit Remove="@(WasmComponentTypeWit)" />
    </ItemGroup>
  </Target>
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM" Version="10.0.0-rc.1.26357.1" />
    <PackageReference Include="runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM" Version="10.0.0-rc.1.26357.1" />
  </ItemGroup>
  <ItemGroup>
    <TrimmerRootAssembly Include="$(MSBuildProjectName)" />
  </ItemGroup>
</Project>
