package custom:game;

interface game-api {
    add-buff: func(unit-id: s32, buff-id: string, duration: f32);
    add-leaderboard-row: func(label: string, value: string, color-r: f32, color-g: f32, color-b: f32, color-has-color: bool);
    add-unit-type-ability: func(unit-type-id: string, ability-id: string);
    adjust-player-gold: func(player-index: s32, delta: f32);
    adjust-player-wood: func(player-index: s32, delta: f32);
    broadcast-message: func(message: string);
    cancel-timer: func(timer-handle: s32);
    cast-ability: func(unit-id: s32, ability-id: string, target-position-x: f32, target-position-y: f32, target-position-z: f32);
    clear-leaderboard: func();
    clear-selection: func();
    count-units-owned-by-player: func(player-index: s32) -> s32;
    create-floating-text: func(text: string, position-x: f32, position-y: f32, position-z: f32, color-x: f32, color-y: f32, color-z: f32, duration: f32);
    define-zone: func(min-x: f32, min-z: f32, max-x: f32, max-z: f32) -> s32;
    destroy-unit: func(unit-id: s32);
    generate-map-directory: func(map-name: string, target-directory: string);
    get-ability-cooldown: func(unit-id: s32, ability-id: string) -> f32;
    get-all-units: func() -> list<s32>;
    get-castle: func(is-enemy: bool) -> s32;
    get-coordinate-max-x: func(coordinate-name: string) -> f32;
    get-coordinate-max-y: func(coordinate-name: string) -> f32;
    get-coordinate-max-z: func(coordinate-name: string) -> f32;
    get-coordinate-min-x: func(coordinate-name: string) -> f32;
    get-coordinate-min-y: func(coordinate-name: string) -> f32;
    get-coordinate-min-z: func(coordinate-name: string) -> f32;
    get-current-population: func() -> s32;
    get-game-elapsed-time: func() -> f32;
    get-gold: func() -> f32;
    get-max-population: func() -> s32;
    get-modifiers-count: func(unit-id: s32) -> s32;
    get-modifiers-get: func(unit-id: s32, index: s32) -> string;
    get-player-count: func() -> s32;
    get-player-current-population: func(player-index: s32) -> s32;
    get-player-gold: func(player-index: s32) -> f32;
    get-player-kills: func(player-index: s32) -> s32;
    get-player-max-population: func(player-index: s32) -> s32;
    get-player-name: func(player-index: s32) -> string;
    get-player-start-location-x: func(player-index: s32) -> f32;
    get-player-start-location-y: func(player-index: s32) -> f32;
    get-player-start-location-z: func(player-index: s32) -> f32;
    get-player-team: func(player-index: s32) -> s32;
    get-player-wood: func(player-index: s32) -> f32;
    get-resource-node: func(index: s32) -> s32;
    get-resource-node-count: func() -> s32;
    get-selected-units: func() -> list<s32>;
    get-stone: func() -> f32;
    get-unit-by-id: func(unique-id: s32) -> s32;
    get-unit-route-state: func(unit-id: s32) -> s32;
    get-units-in-radius: func(center-x: f32, center-y: f32, center-z: f32, radius: f32) -> list<s32>;
    get-units-owned-by-player: func(player-index: s32) -> list<s32>;
    get-wood: func() -> f32;
    get-zone-center-x: func(zone-handle: s32) -> f32;
    get-zone-center-y: func(zone-handle: s32) -> f32;
    get-zone-center-z: func(zone-handle: s32) -> f32;
    has-coordinate: func(coordinate-name: string) -> bool;
    is-player-active: func(player-index: s32) -> bool;
    is-player-computer: func(player-index: s32) -> bool;
    is-position-in-coordinate: func(position-x: f32, position-y: f32, position-z: f32, coordinate-name: string) -> bool;
    issue-attack-move-order: func(unit-id: s32, destination-x: f32, destination-y: f32, destination-z: f32);
    issue-attack-move-order-to-player: func(player-index: s32, destination-x: f32, destination-y: f32, destination-z: f32);
    issue-cast-order: func(caster-id: s32, ability-id: string, target-id: s32);
    issue-cast-order-at: func(caster-id: s32, ability-id: string, position-x: f32, position-y: f32, position-z: f32);
    issue-move-order: func(unit-id: s32, destination-x: f32, destination-y: f32, destination-z: f32);
    kill-unit: func(unit-id: s32);
    pan-camera-to: func(position-x: f32, position-y: f32, position-z: f32, duration: f32);
    ping-minimap: func(position-x: f32, position-y: f32, position-z: f32);
    play-click-sound: func();
    play-warning-sound: func();
    random-float: func(min: f32, max: f32) -> f32;
    random-int: func(min: s32, max: s32) -> s32;
    read-saved-data: func(file-name: string) -> string;
    register-ability: func(ability-id: string, display-name: string, tooltip: string, icon-path: string, is-instant: bool);
    register-buff-modifier: func(buff-id: string, stat-name: string, is-percentage: bool, value: f32);
    remove-buff: func(unit-id: s32, buff-id: string);
    resource-node-count: func() -> s32;
    resource-node-is-depleted: func(id: s32) -> bool;
    resource-node-position-x: func(id: s32) -> f32;
    resource-node-position-y: func(id: s32) -> f32;
    resource-node-position-z: func(id: s32) -> f32;
    resource-node-resource-amount: func(id: s32) -> f32;
    resource-node-resource-type: func(id: s32) -> string;
    schedule-repeating-timer: func(interval: f32) -> s32;
    schedule-timer: func(delay: f32) -> s32;
    select-unit: func(unit-id: s32);
    send-message-to-player: func(player-index: s32, message: string);
    set-ability-auto-cast: func(unit-id: s32, ability-id: string, active: bool);
    set-ability-cooldown: func(unit-id: s32, ability-id: string, cooldown: f32);
    set-ability-grid-position: func(ability-id: string, x: s32, y: s32);
    set-ability-icon: func(ability-id: string, icon-path: string);
    set-ability-instant: func(ability-id: string, is-instant: bool);
    set-ability-tooltip: func(ability-id: string, tooltip: string);
    set-countdown-timer-label: func(label: string);
    set-day-night-cycle-enabled: func(enabled: bool);
    set-gold: func(val: f32);
    set-leaderboard-value: func(label: string, value: string);
    set-leaderboard-visible: func(title: string, visible: bool);
    set-max-population: func(val: s32);
    set-player-computer-controlled: func(player-index: s32, is-proxy: bool);
    set-player-gold: func(player-index: s32, amount: f32);
    set-player-kills: func(player-index: s32, kills: s32);
    set-player-max-population: func(player-index: s32, max: s32);
    set-player-team: func(player-index: s32, team-index: s32);
    set-player-wood: func(player-index: s32, amount: f32);
    set-players-allied: func(player-index: s32, other-player-index: s32, allied: bool);
    set-resource-node-resource-amount: func(id: s32, val: f32);
    set-stone: func(val: f32);
    set-time-of-day: func(time: f32);
    set-unit-armor: func(id: s32, val: f32);
    set-unit-color: func(unit-id: s32, color-x: f32, color-y: f32, color-z: f32);
    set-unit-damage: func(id: s32, val: f32);
    set-unit-experience: func(id: s32, val: f32);
    set-unit-health: func(id: s32, val: f32);
    set-unit-invulnerable: func(id: s32, val: bool);
    set-unit-is-enemy: func(id: s32, val: bool);
    set-unit-level: func(unit-id: s32, level: s32);
    set-unit-mana: func(id: s32, val: f32);
    set-unit-max-health: func(id: s32, val: f32);
    set-unit-max-mana: func(id: s32, val: f32);
    set-unit-name: func(id: s32, val: string);
    set-unit-owner: func(unit-id: s32, player-index: s32);
    set-unit-player: func(id: s32, val: s32);
    set-unit-potions: func(id: s32, val: s32);
    set-unit-range: func(id: s32, val: f32);
    set-unit-route-state: func(unit-id: s32, state: s32);
    set-unit-scale: func(id: s32, val: f32);
    set-unit-speed: func(id: s32, val: f32);
    set-unit-spell-immune: func(unit-id: s32, immune: bool);
    set-wood: func(val: f32);
    shake-camera: func(intensity: f32, duration: f32);
    show-feedback-text: func(text: string, color-x: f32, color-y: f32, color-z: f32);
    spawn-projectile: func(projectile-type-id: string, start-x: f32, start-y: f32, start-z: f32, target-x: f32, target-y: f32, target-z: f32, speed: f32);
    spawn-resource-node: func(resource-type: string, position-x: f32, position-y: f32, position-z: f32, amount: f32);
    spawn-target-indicator: func(position-x: f32, position-y: f32, position-z: f32, color-x: f32, color-y: f32, color-z: f32);
    spawn-unit: func(unit-type-id: string, position-x: f32, position-y: f32, position-z: f32, is-enemy: bool, bypass-population: bool) -> s32;
    spawn-unit-for-player: func(unit-type-id: string, position-x: f32, position-y: f32, position-z: f32, player-index: s32) -> s32;
    spawn-visual-effect: func(effect-type-id: string, position-x: f32, position-y: f32, position-z: f32, scale: f32);
    start-building-placement: func(unit-type-id: string);
    start-countdown-timer: func(duration: f32, label: string);
    stop-countdown-timer: func();
    trigger-defeat: func();
    trigger-player-defeat: func(player-index: s32, reason: string);
    trigger-player-victory: func(player-index: s32);
    trigger-victory: func();
    unit-add-buff: func(id: s32, buff-id: string, duration: f32);
    unit-add-item: func(id: s32, item-id: string) -> bool;
    unit-armor: func(id: s32) -> f32;
    unit-attack: func(id: s32, target-id: s32);
    unit-attack-move: func(id: s32, destination-x: f32, destination-y: f32, destination-z: f32);
    unit-damage: func(id: s32) -> f32;
    unit-experience: func(id: s32) -> f32;
    unit-gather: func(id: s32, resource-node-id: s32);
    unit-get-custom-data: func(id: s32, key: string) -> string;
    unit-get-items-count: func(id: s32) -> s32;
    unit-get-items-get: func(id: s32, index: s32) -> string;
    unit-get-modifiers-count: func(id: s32) -> s32;
    unit-get-modifiers-get: func(id: s32, index: s32) -> string;
    unit-gold-bounty: func(id: s32) -> f32;
    unit-has-buff: func(id: s32, buff-id: string) -> bool;
    unit-has-custom-data: func(id: s32, key: string) -> bool;
    unit-has-item: func(id: s32, item-id: string) -> bool;
    unit-health: func(id: s32) -> f32;
    unit-hold-position: func(id: s32);
    unit-invulnerable: func(id: s32) -> bool;
    unit-is-building: func(id: s32) -> bool;
    unit-is-dead: func(id: s32) -> bool;
    unit-is-enemy: func(id: s32) -> bool;
    unit-is-hero: func(id: s32) -> bool;
    unit-level: func(id: s32) -> s32;
    unit-mana: func(id: s32) -> f32;
    unit-max-health: func(id: s32) -> f32;
    unit-max-mana: func(id: s32) -> f32;
    unit-move-to: func(id: s32, destination-x: f32, destination-y: f32, destination-z: f32);
    unit-name: func(id: s32) -> string;
    unit-player: func(id: s32) -> s32;
    unit-position-x: func(id: s32) -> f32;
    unit-position-y: func(id: s32) -> f32;
    unit-position-z: func(id: s32) -> f32;
    unit-potions: func(id: s32) -> s32;
    unit-range: func(id: s32) -> f32;
    unit-remove-buff: func(id: s32, buff-id: string);
    unit-remove-custom-data: func(id: s32, key: string) -> bool;
    unit-remove-item: func(id: s32, item-id: string) -> bool;
    unit-scale: func(id: s32) -> f32;
    unit-set-custom-data: func(id: s32, key: string, value: string);
    unit-silence: func(id: s32, duration: f32);
    unit-speed: func(id: s32) -> f32;
    unit-stop: func(id: s32);
    unit-stun: func(id: s32, duration: f32);
    unit-teleport: func(id: s32, position-x: f32, position-y: f32, position-z: f32);
    unit-unit-id: func(id: s32) -> string;
    unit-xp-bounty: func(id: s32) -> f32;
    upgrade-unit: func(unit-id: s32);
    write-saved-data: func(file-name: string, content: string);
}

world game-client {
    import game-api;
}
